countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua And Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Myanmar',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Drc',
    'Costa Rica',
    "Côte D'Ivoire",
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Estonia',
    'Swaziland',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'South Korea',
    'Kuwait',
    'Kyrgyzstan',
    "Lao People'S Democratic Republic",
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts And Nevis',
    'Saint Lucia',
    'Saint Vincent And The Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome And Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Trinidad And Tobago',
    'Tunisia',
    'Turkey',
    'United States',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
]

states = [
  'California',
  'Texas',
  'Florida',
  'New York',
  'Illinois',
  'Pennsylvania',
  'Georgia',
  'Ohio',
  'New Jersey',
  'North Carolina',
  'Michigan',
  'Arizona',
  'Tennessee',
  'Indiana',
  'Massachusetts',
  'Virginia',
  'Wisconsin',
  'Minnesota',
  'Missouri',
  'South Carolina',
  'Alabama',
  'Colorado',
  'Louisiana',
  'Maryland',
  'Kentucky',
  'Oklahoma',
  'Washington',
  'Utah',
  'Iowa',
  'Connecticut',
  'Arkansas',
  'Nevada',
  'Mississippi',
  'Kansas',
  'Nebraska',
  'New Mexico',
  'Oregon',
  'Idaho',
  'West Virginia',
  'Rhode Island',
  'South Dakota',
  'Montana',
  'North Dakota',
  'Delaware',
  'New Hampshire',
  'Maine',
  'Alaska',
  'Wyoming',
  'District Of Columbia',
  'Hawaii',
  'Vermont',
  'Puerto Rico',
  'Guam',
  'Virgin Islands',
  'Northern Mariana Islands',
  'American Samoa'
]

provinces = [
  'Australian Capital Territory',
  'New South Wales',
  'Northern Territory',
  'Queensland',
  'South Australia',
  'Tasmania',
  'Victoria',
  'Western Australia',
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland And Labrador',
  'Northwest Territories',
  'Nova Scotia',
  'Nunavut',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Repatriated Travellers',
  'Saskatchewan',
  'Yukon',
  'Anhui',
  'Beijing',
  'Chongqing',
  'Fujian',
  'Gansu',
  'Guangdong',
  'Guangxi',
  'Guizhou',
  'Hainan',
  'Hebei',
  'Heilongjiang',
  'Henan',
  'Hong Kong',
  'Hubei',
  'Hunan',
  'Inner Mongolia',
  'Jiangsu',
  'Jiangxi',
  'Jilin',
  'Liaoning',
  'Macau',
  'Ningxia',
  'Qinghai',
  'Shaanxi',
  'Shandong',
  'Shanghai',
  'Shanxi',
  'Sichuan',
  'Tianjin',
  'Tibet',
  'Unknown',
  'Xinjiang',
  'Yunnan',
  'Zhejiang',
  'Faroe Islands',
  'Greenland',
  'French Guiana',
  'French Polynesia',
  'Guadeloupe',
  'Martinique',
  'Mayotte',
  'New Caledonia',
  'Reunion',
  'Saint Barthelemy',
  'Saint Pierre And Miquelon',
  'St Martin',
  'Wallis And Futuna',
  'Aruba',
  'Bonaire, Sint Eustatius And Saba',
  'Curacao',
  'Sint Maarten',
  'Cook Islands',
  'Anguilla',
  'Bermuda',
  'British Virgin Islands',
  'Cayman Islands',
  'Channel Islands',
  'Falkland Islands (Malvinas)',
  'Gibraltar',
  'Isle Of Man',
  'Montserrat',
  'Saint Helena, Ascension And Tristan Da Cunha',
  'Turks And Caicos Islands'
]

places = [
    *states,
    *countries,
    *provinces
]